# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zysl3jZVbl3xFu-S7xvInvIx29BkeAXF
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import linregress
import matplotlib.pyplot as plt

st.title("📊 Análise de Produção x Diâmetro")

# --- Entrada de dados editável ---
st.subheader("Entrada de dados")

# Caixas de texto para valores separados por vírgula
producoes_input = st.text_input("Produções (separadas por vírgula)", "0,9077,20443,32649,47798,69231")
diametros_input = st.text_input("Diâmetros (separados por vírgula)", "190.70,188.20,186.35,183.88,181.40,178.20")

# Converter para listas numéricas
X = np.array([int(x.strip()) for x in producoes_input.split(",") if x.strip() != ""])
Y = np.array([float(y.strip()) for y in diametros_input.split(",") if y.strip() != ""])

# --- Mostrar tabela de dados ---
st.subheader("Tabela de dados coletados")
tabela_entrada = pd.DataFrame({
    "Produção (unidades)": X,
    "Diâmetro (mm)": Y
})
st.table(tabela_entrada)

# --- Regressão linear ---
slope, intercept, r_value, p_value, std_err = linregress(X, Y)

# Classificação da correlação
if r_value > 0.7:
    classificacao = "Altamente positiva"
elif r_value > 0.3:
    classificacao = "Positiva"
elif r_value > -0.3:
    classificacao = "Sem correlação linear"
elif r_value > -0.7:
    classificacao = "Negativa"
else:
    classificacao = "Altamente negativa"

# --- Resultados em tabela ---
st.subheader("Resultados da regressão e correlação")
tabela_resultados = pd.DataFrame({
    "Parâmetro": [
        "Intercepto (b)",
        "Coeficiente angular (a)",
        "Correlação (R)",
        "p-valor",
        "Erro padrão do slope",
        "Classificação da correlação"
    ],
    "Valor": [
        intercept,
        slope,
        r_value,
        p_value,
        std_err,
        classificacao
    ]
})
st.table(tabela_resultados)

# --- Gráfico ---
st.subheader("Gráfico dos pontos e reta ajustada")
plt.scatter(X, Y, label="Dados medidos", color="blue")
plt.plot(X, intercept + slope*X, color="red", label="Reta ajustada")
plt.xlabel("Produção (unidades)")
plt.ylabel("Diâmetro (mm)")
plt.legend()
st.pyplot(plt)