# -*- coding: utf-8 -*-
"""site.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNsvSo9YbpxZ-UskqdQwuMyA2EgwxG8T
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

st.title("📊 Análise de Produção x Diâmetro")

# --- Entrada de dados em formato de tabela editável ---
st.subheader("Entrada de dados")

dados_iniciais = pd.DataFrame({
    "Produção (unidades)": [0, 9077, 20443, 32649, 47798, 69231],
    "Diâmetro (mm)": [190.70, 188.20, 186.35, 183.88, 181.40, 178.20]
})

# Editor de tabela interativo
tabela_editada = st.data_editor(dados_iniciais, num_rows="dynamic")

# Extrair valores
X = tabela_editada["Produção (unidades)"].to_numpy()
Y = tabela_editada["Diâmetro (mm)"].to_numpy()

# --- Regressão linear ---
result = linregress(X, Y)
slope = result.slope
intercept = result.intercept
r_value = result.rvalue
p_value = result.pvalue
std_err = result.stderr

# Classificação da correlação
if r_value > 0.7:
    classificacao = "Altamente positiva"
elif r_value > 0.3:
    classificacao = "Positiva"
elif r_value > -0.3:
    classificacao = "Sem correlação linear"
elif r_value > -0.7:
    classificacao = "Negativa"
else:
    classificacao = "Altamente negativa"

# --- Resultados em tabela ---
st.subheader("Resultados da regressão e correlação")
tabela_resultados = pd.DataFrame({
    "Parâmetro": [
        "Intercepto (b)",
        "Coeficiente angular (a)",
        "Correlação (R)",
        "p-valor",
        "Erro padrão do slope",
        "Classificação da correlação"
    ],
    "Valor": [
        intercept,
        slope,
        r_value,
        p_value,
        std_err,
        classificacao
    ]
})
st.table(tabela_resultados)

# --- Previsão para diâmetro alvo ---
Y_target = st.number_input("Defina o diâmetro alvo (mm)", value=168.0)
X_target = (Y_target - intercept) / slope

st.write(f"📌 Produção necessária para atingir {Y_target:.1f} mm: **{X_target:.0f} unidades**")

# --- Gráfico ---
st.subheader("Gráfico dos pontos e reta ajustada")
Y_pred = intercept + slope * X

plt.figure(figsize=(8,5))
plt.scatter(X, Y, color='blue', label='Dados coletados')
plt.plot(X, Y_pred, color='red', label='Regressão linear')
plt.scatter(X_target, Y_target, color='green', marker='x', s=120, label=f"Alvo: {Y_target} mm")
plt.text(X_target, Y_target+1, f"{int(X_target)} un", color='green')

plt.xlabel("Produção (unidades)")
plt.ylabel("Diâmetro (mm)")
plt.title("Produção vs Diâmetro: regressão linear e alvo")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

st.pyplot(plt)